x,y,z="red","orange","black"
print(x)
print(y)
print(z)
#####-------------
x=y=z="orange"
print(x)
print(y)
print(z)
#####--------------
fruits=["orange","red","black"]
x,y,z=fruits
print(x)
print(y)
print(z)